chargehive/configuration

- cmd/cmd.go
- object/object.go
- utils/clean.go
- utils/clean_test.go
- v1/scheduler/initiator.go
> Added formatting fixes to cmd

- docs/selectors.md
- selector/key.go
Added selector keys for connector ID and connector library
> Added connector selector keys

- object/metadata.go
removed validation on projectID so that an empty id is valid
> ProjectID Validation

- connectorconfig/paysafe.go
- connectorconfig/paysafeapplepay.go
- connectorconfig/paysafegooglepay.go
- utils/generate.go
- utils/validate_test.go
Added tests for string* validation on secure fields
> String Pointer Validation

- connectorconfig/authorize.go
- connectorconfig/braintree.go
- connectorconfig/chargehive.go
- connectorconfig/credentials.go
- connectorconfig/cybersource.go
- connectorconfig/maxmind.go
- connectorconfig/paypalexpresscheckout.go
- connectorconfig/paypalwebsitepaymentspro.go
- connectorconfig/paysafe.go
- connectorconfig/paysafeapplepay.go
- connectorconfig/paysafegooglepay.go
- connectorconfig/qualpay.go
- connectorconfig/sandbox.go
- connectorconfig/stripe.go
- connectorconfig/vindicia.go
- connectorconfig/worldpay.go
added supportsApplePay interface method
> Supports ApplePay Interface Method

- connectorconfig/worldpay.go
- utils/generate.go
Added worldpay ApplePay support, validation and generators
> Worldpay ApplePay

- selector/key.go
Added KeyChargePlacementID to charge meta
> Added KeyChargePlacementID to charge meta

- connectorconfig/applePay.go
- connectorconfig/credentials.go
- connectorconfig/worldpay.go
- go.mod
- utils/generate.go
Fixed more missing code and updated applepay to be an embedded struct to be used in other connectors
> Apple pay update

- connectorconfig/applePay.go
- utils/generate.go
Additional options for applepay
> Applepay fields

- v1/connector/connector.go
Added validation for paysafe-accountupdater to library validation
Removed non-existing libraries
> added paysafe-accountupdater to connector validation

- docs/scheduler/on_demand.md
- docs/scheduler/on_trigger.md
- docs/scheduler/sequential.md
- v1/scheduler/enums.go
- v1/scheduler/schedule.go
Added TimeDelaySyncNone to the options and standardized the hour specification to be 0-23
Updated docs
> TimeDelaySyncNone Added

- go.mod
> ProtoBuf Fix

- go.mod
- go.sum
upgraded proto to latest version
> Proto Upgrade

- paymentmethod/const.go
Adds
```InfoKeyCardNumberLength InfoKey = "card_number_length"```
> adds card length info key

- selector/key.go
added payment method info keys
> PaymentMethodInfo Keys

- connectorconfig/vindicia.go
- go.sum
- utils/generate.go
- utils/validate.go
- utils/validate_test.go
- Fixed charge.label validation to allow additional keys
- added test for charge.label.xxxxx
- fixed vindicia generation code to pass tests
> Vindicia Generation and Charge.Label fix

- docs/selectors.md
- selector/key.go
Added method and connector cascade counters to keys
> Cascade Keys

- v1/scheduler/attempt_config.go
instruct assemble to tokenize payment methods
> add ShouldTokenize to AttemptConfig

- v1/connector/connector.go
add "tokenex-api-accountupdater" as a valid library type
> Fix Library validation

- connectorconfig/connector.go
- utils/validate.go
- v1/connector/connector.go
to ignore configuration bytes if a configurationID is set and vice versa
> Implement robust validation 
